[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "./netlify/plugins/restore-sitemap"

[dev]
  command = "npm run dev"
  port = 3000
