const purgecss = require('@fullhuman/postcss-purgecss');
const pxtorem = require('postcss-pxtorem');

module.exports = {
  plugins: [
    pxtorem({
      rootValue: 16,
      propList: ['*', '!border*', '!border-radius', '!font-size', '!box-shadow', '!text-shadow', '!transform'],
      mediaQuery: false,
      minPixelValue: 0
    }),
    ...(process.env.NODE_ENV === 'production'
      ? [purgecss({
          content: [
            './index.html',
            './src/**/*.{jsx,js,tsx,ts}',
          ],
          safelist: {
            standard: [
              /^w-hidden$/,
              /^w-show$/,
              /^w-tablet$/,
              /^w-mobile-/,
              /^w-id$/,
              /^w-latency$/,
              /^w-style$/,
              /^w-y$/,
              /^w-scrolling$/,
              /^w-script$/,
              /^w-action$/,
              /^w-body$/,
              /^w-excerpt$/,
              /^w-image$/,
              /^w-meta$/,
              /^w-readtime$/,
              /^w-tag$/,
              /^w-title$/,
              /^w--next$/,
              /^w--open$/,
              /^w--current$/,
              /^w--active$/,
              /^w--tab-active$/,
              /^w--vertical$/,
              /^w--large$/,
              /^w-icon-/,
              /^is-/,
              /^menu--/,
              /^lenis/,
              /^swiper/,
              /^eapps/,
              /^elfsight/,
              /^pt-/,
              /^html/,
            ],
            deep: [
              /modal/,
              /overlay/,
              /faq_/,
              /partners_/,
              /team_image/,
              /work_image/,
              /work-item/,
              /projects_/,
              /nav_/,
              /nav-/,
              /menu_icon/,
              /hamburger/,
              /line-separate/,
              /header-animation/,
              /heading_/,
              /heading-style/,
              /text-button/,
              /text-size/,
              /text-color/,
              /button-base/,
              /services_/,
              /service_/,
              /testemonials/,
              /footer_/,
              /articles-promo/,
              /social-section/,
              /blog-component/,
              /swiper_blog/,
              /cta-/,
              /formtext/,
              /typeform/,
              /background-video/,
              /hero_/,
              /hero-reveal/,
              /infinity_/,
              /about_/,
              /section_/,
              /container/,
              /padding-/,
              /overflow-/,
              /subtitle/,
              /background-color/,
              /hide-/,
              /show-/,
              /count-up/,
              /arrow_/,
              /page-wrapper/,
              /main-wrapper/,
            ],
            greedy: [
              /data-w-id/,
              /w-mod/,
              /w-nav/,
              /w-dyn/,
              /w-inline/,
              /w-clearfix/,
              /w-embed/,
              /w-background/,
            ],
          },
        })]
      : []),
  ],
};
