import purgecss from '@fullhuman/postcss-purgecss';

export default {
  plugins: [
    ...(process.env.NODE_ENV === 'production'
      ? [purgecss({
          content: [
            './index.html',
            './*.jsx',
            './*.js',
            './*.tsx',
            './*.ts',
          ],
          safelist: {
            standard: [
              /^w-/,
              /^is-/,
              /^menu--/,
              /^lenis/,
              /^swiper/,
              /^eapps/,
              /^elfsight/,
              /^pt-/,
              /^html/,
            ],
            deep: [
              /modal/,
              /overlay/,
              /faq_/,
              /partners_/,
              /team_image/,
              /work_image/,
              /work-item/,
              /projects_/,
              /nav_/,
              /nav-/,
              /menu_icon/,
              /hamburger/,
              /line-separate/,
              /header-animation/,
              /heading_/,
              /heading-style/,
              /text-button/,
              /text-size/,
              /text-color/,
              /button-base/,
              /services_/,
              /service_/,
              /testemonials/,
              /footer_/,
              /articles-promo/,
              /social-section/,
              /blog-component/,
              /swiper_blog/,
              /cta-/,
              /formtext/,
              /typeform/,
              /background-video/,
              /hero_/,
              /infinity_/,
              /about_/,
              /section_/,
              /container/,
              /padding-/,
              /overflow-/,
              /subtitle/,
              /background-color/,
              /hide-/,
              /show-/,
              /count-up/,
              /arrow_/,
              /page-wrapper/,
              /main-wrapper/,
            ],
            greedy: [
              /data-w-id/,
              /w-mod/,
              /w-nav/,
              /w-dyn/,
              /w-inline/,
              /w-clearfix/,
              /w-embed/,
              /w-background/,
            ],
          },
        })]
      : []),
  ],
};
