import assert from 'node:assert/strict';
import test from 'node:test';

import { buildSystemPrompt } from '../../../../../src/backend/rag/application/llm/prompts/answering.js';
import { buildIntentFallbackPrompt } from '../../../../../src/backend/rag/application/llm/prompts/fallback.js';
import { buildInsufficientContextPrompt } from '../../../../../src/backend/rag/application/llm/prompts/insufficientcontext.js';
import { buildIntentPrompt } from '../../../../../src/backend/rag/application/llm/prompts/intent.js';
import { buildRetrievalPlanPrompt } from '../../../../../src/backend/rag/application/llm/prompts/retrievalplan.js';

const COMPANY_NAME = 'ARG Software';

test('answer prompt establishes Gaspar as the first-person speaker', () => {
  const prompt = buildSystemPrompt(COMPANY_NAME, 'en');

  assert.match(prompt, /You are Gaspar/u);
  assert.match(prompt, /Always speak as Gaspar in the first person/u);
  assert.match(prompt, /never say you are not Gaspar/u);
  assert.match(prompt, /Facts about Gaspar in the provided context are facts about you/u);
  assert.match(prompt, /Never describe yourself as an AI assistant/u);
  assert.doesNotMatch(prompt, /You are the public website assistant/u);
});

test('answer prompt applies assistant language policy', () => {
  const prompt = buildSystemPrompt(COMPANY_NAME, 'pt-PT');

  assert.match(prompt, /answer in any human language, answer positively/u);
  assert.match(prompt, /Do not infer native language or fluency/u);
  assert.match(prompt, /birthplace, nationality, or ascendence/u);
});

test('answer prompt separates Gaspar output from evidence of ARG capability', () => {
  const prompt = buildSystemPrompt(COMPANY_NAME, 'en');

  assert.match(prompt, /technical task as a way of evaluating ARG/u);
  assert.match(prompt, /Gaspar is an AI assistant/u);
  assert.match(prompt, /generated by Gaspar is not evidence of ARG's engineering competence/u);
  assert.match(prompt, /evidence genuinely attributable to ARG/u);
  assert.match(prompt, /Do not request contact information/u);
  assert.match(prompt, /substantively supports the response/u);
});

test('Gaspar prompts handle visitor names conversationally', () => {
  const answerPrompt = buildSystemPrompt(COMPANY_NAME, 'en');
  const smallTalkPrompt = buildIntentFallbackPrompt(COMPANY_NAME, 'small_talk', 'en');
  const intentPrompt = buildIntentPrompt(COMPANY_NAME);

  assert.match(answerPrompt, /ask for their name/u);
  assert.match(answerPrompt, /address them by that name naturally/u);
  assert.match(answerPrompt, /do not immediately pivot to generic help copy/u);

  assert.match(smallTalkPrompt, /address them by that name naturally/u);
  assert.match(smallTalkPrompt, /ask for their name/u);
  assert.match(smallTalkPrompt, /does not make the response feel transactional/u);

  assert.match(intentPrompt, /visitor name introductions/u);
  assert.match(intentPrompt, /just the visitor sharing their name/u);
  assert.match(intentPrompt, /do not immediately pivot to generic help copy/u);
});

test('fallback prompt keeps small-talk and unsupported responses in Gaspar persona', () => {
  const smallTalkPrompt = buildIntentFallbackPrompt(COMPANY_NAME, 'small_talk', 'en');
  const unsupportedPrompt = buildIntentFallbackPrompt(COMPANY_NAME, 'unsupported', 'en');

  assert.match(smallTalkPrompt, /You are Gaspar/u);
  assert.match(smallTalkPrompt, /Never describe yourself as an AI assistant/u);
  assert.doesNotMatch(smallTalkPrompt, /You are the public website assistant/u);

  assert.match(unsupportedPrompt, /You are Gaspar/u);
  assert.match(unsupportedPrompt, /share the relevant requirements here/u);
  assert.match(unsupportedPrompt, /optional next steps/u);
  assert.match(unsupportedPrompt, /Do not request contact information/u);
  assert.doesNotMatch(unsupportedPrompt, /send a message through Gaspar/u);
});

test('insufficient-context prompt stays in Gaspar persona', () => {
  const prompt = buildInsufficientContextPrompt(COMPANY_NAME, 'en');

  assert.match(prompt, /You are Gaspar/u);
  assert.match(prompt, /Never describe yourself as an AI assistant/u);
  assert.match(prompt, /share those requirements here/u);
  assert.match(prompt, /optional next steps/u);
  assert.match(prompt, /do not request contact information/u);
  assert.doesNotMatch(prompt, /You are the public website assistant/u);
  assert.doesNotMatch(prompt, /send a message through Gaspar/u);
});

test('intent prompt requires direct response text to be spoken by Gaspar', () => {
  const prompt = buildIntentPrompt(COMPANY_NAME);

  assert.match(prompt, /website voice, Gaspar/u);
  assert.match(prompt, /response text you return is spoken by Gaspar in the first person/u);
  assert.match(prompt, /Never describe the speaker as an AI assistant/u);
  assert.match(prompt, /whether the speaker is an AI, robot, chatbot, language model, or real/u);
  assert.doesNotMatch(prompt, /^You route messages for [^.]*public website assistant\./u);
});

test('intent prompt separates answer rewrites from source-grounded summaries', () => {
  const prompt = buildIntentPrompt(COMPANY_NAME);

  assert.match(prompt, /conversation_transform means/u);
  assert.match(prompt, /make it brief/u);
  assert.match(prompt, /I did not understand/u);
  assert.match(prompt, /Do not use conversation_transform when the visitor asks to summarize or explain a specific source/u);
  assert.match(prompt, /article or blog summaries/u);
});

test('intent and retrieval prompts recognize pre-sales capability tests', () => {
  const intentPrompt = buildIntentPrompt(COMPANY_NAME);
  const retrievalPrompt = buildRetrievalPlanPrompt();

  assert.match(intentPrompt, /technical task to evaluate ARG/u);
  assert.match(intentPrompt, /rag_question, not unsupported/u);
  assert.match(intentPrompt, /purpose to capability_evaluation/u);
  assert.match(intentPrompt, /translating it internally/u);
  assert.match(intentPrompt, /purpose labels are always English/u);
  assert.match(retrievalPrompt, /capability demonstration or pre-sales test/u);
  assert.match(retrievalPrompt, /attributable ARG evidence/u);
  assert.match(retrievalPrompt, /Do not plan retrieval for generating the requested artifact/u);
  assert.match(retrievalPrompt, /separate direct_evidence question for each independently evidenced subject/u);
  assert.match(retrievalPrompt, /Do not combine the complete stack into one exact technology phrase/u);
});

test('retrieval planner treats direct AI and robot questions as Gaspar profile questions', () => {
  const prompt = buildRetrievalPlanPrompt();

  assert.match(prompt, /For Gaspar identity or profile questions/u);
  assert.match(prompt, /whether you are an AI, robot, chatbot, language model, or real/u);
  assert.match(prompt, /use entity "Gaspar" and subject "assistant profile"/u);
});
